# Source: https://gitlab.com/european-data-portal/edp-vocabularies/-/blob/master/edp-non-proprietary-format.rdf?ref_type=heads

NON_PROPRIETARY_VOCABULARY = {
    "http://publications.europa.eu/resource/authority/file-type/BMP",
    "http://publications.europa.eu/resource/authority/file-type/CSV",
    "http://publications.europa.eu/resource/authority/file-type/DBF",
    "http://publications.europa.eu/resource/authority/file-type/GEOJSON",
    "http://publications.europa.eu/resource/authority/file-type/GZIP",
    "http://publications.europa.eu/resource/authority/file-type/HTML",
    "http://publications.europa.eu/resource/authority/file-type/ICS",
    "http://publications.europa.eu/resource/authority/file-type/JPEG2000",
    "http://publications.europa.eu/resource/authority/file-type/JSON",
    "http://publications.europa.eu/resource/authority/file-type/JSON_LD",
    "http://publications.europa.eu/resource/authority/file-type/KML",
    "http://publications.europa.eu/resource/authority/file-type/KMZ",
    "http://publications.europa.eu/resource/authority/file-type/NETCDF",
    "http://publications.europa.eu/resource/authority/file-type/ODS",
    "http://publications.europa.eu/resource/authority/file-type/PNG",
    "http://publications.europa.eu/resource/authority/file-type/RDF_N_QUADS",
    "http://publications.europa.eu/resource/authority/file-type/RDF_N_TRIPLES",
    "http://publications.europa.eu/resource/authority/file-type/RDF_TRIG",
    "http://publications.europa.eu/resource/authority/file-type/RDF_TURTLE",
    "http://publications.europa.eu/resource/authority/file-type/RDF_XML",
    "http://publications.europa.eu/resource/authority/file-type/RSS",
    "http://publications.europa.eu/resource/authority/file-type/RTF",
    "http://publications.europa.eu/resource/authority/file-type/TAR",
    "http://publications.europa.eu/resource/authority/file-type/TIFF",
    "http://publications.europa.eu/resource/authority/file-type/TSV",
    "http://publications.europa.eu/resource/authority/file-type/TXT",
    "http://publications.europa.eu/resource/authority/file-type/WMS_SRVC",
    "http://publications.europa.eu/resource/authority/file-type/XML",
    "http://publications.europa.eu/resource/authority/file-type/ZIP",
}