FROM python:3.9-alpine

# ⚠️ IMPORTANT: Environment variables must be configured in PLESK.
# By default, the Data-loader will access the /shared/ volume. 
# To override this path, set the ENV_SHARED variable.

# Copy Filesystem.
WORKDIR /app/data-loader
COPY . .

# Install requirements.
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run the data-loader.
CMD ["python", "main.py"]
